run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - stylecheck
    - gosimple
    - unused
    - errcheck
    - gosec
    - bodyclose
    - gocyclo
    - misspell
    - gofmt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G304 # Expect file inclusion via variables (CLI tools)
  revive:
    config: revive.toml
  stylecheck:
    checks: ["all"]
